# Generated by Django 3.1.6 on 2021-02-11 03:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitem',
            name='post_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 11, 3, 10, 39, 87253, tzinfo=utc)),
        ),
    ]
