# Generated by Django 3.1.6 on 2021-02-14 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20210211_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='category',
            field=models.CharField(choices=[('Business', 'Business'), ('Lifestyle', 'Lifestyle'), ('Tips', 'Tips'), ('Beauty', 'Beauty')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='post_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 14, 6, 25, 38, 631474, tzinfo=utc)),
        ),
    ]
