# Generated by Django 3.1.6 on 2021-02-14 20:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_auto_20210214_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscibePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='category',
            field=models.CharField(choices=[('Beauty', 'Beauty'), ('Business', 'Business'), ('Tips', 'Tips'), ('Lifestyle', 'Lifestyle')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='post_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 14, 20, 6, 58, 761849, tzinfo=utc)),
        ),
    ]
