# Generated by Django 3.1.6 on 2021-02-14 20:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20210214_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameModel(
            old_name='SubscibePage',
            new_name='SuggestPage',
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='category',
            field=models.CharField(choices=[('Beauty', 'Beauty'), ('Tips', 'Tips'), ('Business', 'Business'), ('Lifestyle', 'Lifestyle')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='post_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 14, 20, 15, 30, 387654, tzinfo=utc)),
        ),
    ]
